name: CI

on:
  push:
    paths-ignore:
      - 'Documentation/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'Documentation/**'
      - '**.md'

jobs:
  build:
    name: PHP linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Install composer dependencies
        run: |
          composer remove ergebnis/composer-normalize --dev --no-update
          composer update --no-progress --prefer-dist --optimize-autoloader
      - name: Run PHP linter
        run: |
          find . -name \*.php  ! -path "./.Build/*" -exec php -l {} \;
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-versions: '7.2'
            typo3-versions: '10'
          - php-versions: '7.4'
            typo3-versions: '11'
          - php-versions: '8.1'
            typo3-versions: '11'
          - php-versions: '8.1'
            typo3-versions: '12'
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Run integration tests
        run: |
          cd .devbox
          ./runIntegrationTests.sh ${{ matrix.typo3-versions }}
        env:
          CYPRESS_IO_KEY: ${{ secrets.CYPRESS_IO_KEY }}
  xliff-validation:
    name: XLIFF validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install package
        run: |
          sudo apt-get -y install libxml2-utils
      - name: Download XSD
        run: |
          curl --no-progress-meter -O https://docs.oasis-open.org/xliff/v1.2/cs02/xliff-core-1.2-strict.xsd
      - name: Validate XLIFF files
        run: |
          xmllint --schema xliff-core-1.2-strict.xsd --noout Resources/Private/Language/*.xlf
